// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgE4Ky6mNKsdPst7EqW1cLZHlPTeUWMyc',
    appId: '1:426138807426:web:84bb2b3a300a2b84e6d89b',
    messagingSenderId: '426138807426',
    projectId: 'flutter-chat-c1381',
    authDomain: 'flutter-chat-c1381.firebaseapp.com',
    storageBucket: 'flutter-chat-c1381.appspot.com',
    measurementId: 'G-BFHWLZ16DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDreeMXJ6Lr0fjHx4LWRrUddCIystEz4jU',
    appId: '1:426138807426:android:1ea90cd984405a45e6d89b',
    messagingSenderId: '426138807426',
    projectId: 'flutter-chat-c1381',
    storageBucket: 'flutter-chat-c1381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN7A4ZYQE67Zq5TlQ4ogYYiWoVapGIQ74',
    appId: '1:426138807426:ios:fef9f441ac0d5346e6d89b',
    messagingSenderId: '426138807426',
    projectId: 'flutter-chat-c1381',
    storageBucket: 'flutter-chat-c1381.appspot.com',
    iosBundleId: 'com.meemong.flutterChat',
  );
}
